name: CI/CD Pipeline

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: Windows

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build the frontend of app
        run: npm run build
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "Shashank7016"
          git config --global user.email "bryanhovak@gmail.com"
          git checkout -b gh-pages
          git add -f build/
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
